### ISSUE TITLE
Unable to view page

### ISSUE THREAD

**Issue by jilenloa** [zone-eu/zmta-webadmin#1]
I have installed this nice package on my server online. Nothing shows after I type http://myserver:8082/. It just loads and no response from the server. I tried changing port numbers, the issue persisted.

**Comment by adityasingh007** [comment]
In config/default.js, set "host" to false.

Also if you have firewall, allow port 8082

`ufw allow 8082`

**Comment by jaskolowski** [comment]
hello,
I have the server running on port 2525 and when install the webadmin this error come up:
`Failed at the zmta-webadmin@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed`

So, my question is: How do I configure my running apache2 to publishing the webadmin as the instruction said that can be configured?
or, first I have to get the webadmin server running for do it?
thanks

**Comment by andris9** [comment]
@jaskolowski this error means that `npm start` command failed but does not state the reason for it. Do you have any more logs about the failure?

**Comment by jaskolowski** [comment]
this is the info that `npm start` output:
 `>zmta-webadmin@1.0.0 start /var/www/html/lista-mta-zone/www
> node server.js

info Express WWW server listening on port 8082
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
    at Object.exports._errnoException (util.js:1050:11)
    at exports._exceptionWithHostPort (util.js:1073:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1093:14)

npm ERR! Linux 3.13.0-119-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
npm ERR! node v7.10.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! zmta-webadmin@1.0.0 start: `node server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the zmta-webadmin@1.0.0 start script 'node server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the zmta-webadmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs zmta-webadmin
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls zmta-webadmin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/.npm/_logs/2017-05-19T18_54_07_930Z-debug.log `


And the log have this:

`0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@4.2.0
3 info using node@v7.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle zmta-webadmin@1.0.0~prestart: zmta-webadmin@1.0.0
6 silly lifecycle zmta-webadmin@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle zmta-webadmin@1.0.0~start: zmta-webadmin@1.0.0
8 verbose lifecycle zmta-webadmin@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle zmta-webadmin@1.0.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/var/www/html/lista-mta-zone/www/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle zmta-webadmin@1.0.0~start: CWD: /var/www/html/lista-mta-zone/www
11 silly lifecycle zmta-webadmin@1.0.0~start: Args: [ '-c', 'node server.js' ]
12 silly lifecycle zmta-webadmin@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle zmta-webadmin@1.0.0~start: Failed to exec start script
14 verbose stack Error: zmta-webadmin@1.0.0 start: `node server.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid zmta-webadmin@1.0.0
16 verbose cwd /var/www/html/lista-mta-zone/www
17 error Linux 3.13.0-119-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
19 error node v7.10.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error zmta-webadmin@1.0.0 start: `node server.js`
23 error Exit status 1
24 error Failed at the zmta-webadmin@1.0.0 start script 'node server.js'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the zmta-webadmin package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     node server.js
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs zmta-webadmin
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls zmta-webadmin
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ] `

**Comment by andris9** [comment]
I would say that your redis connection info is not properly set up. 

    Error: Redis connection to localhost:6379 failed - connect ECONNREFUSED 127.0.0.1:6379

**Comment by Manishjodhani** [comment]
How would we check our redis connection is working or not??
